# -*- coding: utf-8 -*-
"""Vendas - Analise de Sentimento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvA_Y8vTtTEiOx0Fm67VYZOLa9LpLBks
"""

import pandas as pd
from io import StringIO
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# String que contém os dados
dados_sentimento_str = """
ID,Comentario,Sentimento
1,"O serviço de assistência foi rápido e o técnico super atencioso!",Positivo
2,"O carro quebrou de novo, estou muito insatisfeito com a qualidade.",Negativo
3,"O custo é justo, mas a espera foi longa.",Neutro
4,"Melhor experiência que já tive com seguros, recomendo a todos.",Positivo
5,"A ligação caiu e não consegui resolver nada, que frustração.",Negativo
6,"Ótimo atendimento, resolveram o problema em minutos.",Positivo
7,"Não houve retorno, o pior serviço que já contratei.",Negativo
8,"Achei o valor um pouco alto, mas foi eficiente.",Neutro
9,"A equipe foi incrível, nota 10.",Positivo
10,"Problema resolvido com atraso, mas resolvido.",Neutro
"""

df_sentimento = pd.read_csv(StringIO(dados_sentimento_str))

# 1. Definição de Features (X) e Target (y)
X_text = df_sentimento['Comentario']
y = df_sentimento['Sentimento']

# 2. Divisão em Treinamento e Teste
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.3, random_state=42
)

# 3. Vetorização (CountVectorizer)
# Transforma os textos em matrizes de contagem de palavras (Bag-of-Words)
vectorizer = CountVectorizer()
X_train_vectors = vectorizer.fit_transform(X_train_text)
X_test_vectors = vectorizer.transform(X_test_text)

print("--- Pré-processamento e Vetorização Concluídos ---")
print(f"Dimensão dos dados de treino (vetores): {X_train_vectors.shape}")

# O vocabulário criado:
# print("\nVocabulário (Exemplo):")
# print(list(vectorizer.get_feature_names_out())[:10])

# Treinamento do Modelo Naive Bayes
model_nb = MultinomialNB()
model_nb.fit(X_train_vectors, y_train)

# Previsão no Conjunto de Teste
y_pred_nb = model_nb.predict(X_test_vectors)

print("\n--- Relatório de Classificação (Naive Bayes) ---")
print(classification_report(y_test, y_pred_nb))
print(f"Acurácia do Modelo: {accuracy_score(y_test, y_pred_nb):.4f}")

# Exemplo de Previsão em Novo Texto
novo_texto = ["O produto é incrível, superou todas as expectativas!"]
novo_texto_vector = vectorizer.transform(novo_texto)
previsao_novo = model_nb.predict(novo_texto_vector)

print("\n--- Previsão em um Novo Comentário ---")
print(f"Comentário: '{novo_texto[0]}'")
print(f"Sentimento Previsto: **{previsao_novo[0]}**")

# Este código simula a estrutura e as etapas do Deep Learning,
# mas não requer bibliotecas complexas (TensorFlow/PyTorch) para execução.

import numpy as np

# 1. Tokenização e Padding (necessário para a LSTM)
# Transformação das palavras em sequências de números e padronização do tamanho das sequências.
print("1. Tokenização e Padding: Converte texto em sequências numéricas de tamanho fixo.")

# 2. Embedding Layer
# Cada palavra é mapeada para um vetor denso que captura seu significado semântico.
print("2. Embedding Layer: Cria vetores densos (embeddings) de 100 dimensões para cada palavra.")

# 3. LSTM Layer
# A camada LSTM processa a sequência, capturando dependências de longo prazo no texto.
print("3. Camada LSTM: Processa a sequência para entender o contexto e a negação.")

# 4. Dense Layer (Camada Densa)
# Camada de saída que transforma os resultados da LSTM em probabilidades.
print("4. Camada Densa: Mapeia as features contextuais para as 3 classes (Positivo, Negativo, Neutro).")

# --- Previsão Simulada com Deep Learning (Baseada na lógica humana) ---
def prever_sentimento_lstm(texto):
    if "incrível" in texto.lower() or "superou" in texto.lower() or "melhor" in texto.lower() or "nota 10" in texto.lower():
        return "Positivo"
    elif "quebrou" in texto.lower() or "insatisfeito" in texto.lower() or "frustração" in texto.lower() or "pior serviço" in texto.lower():
        return "Negativo"
    else:
        return "Neutro"

novo_texto_lstm = "O produto é incrível, superou todas as expectativas!"
previsao_lstm = prever_sentimento_lstm(novo_texto_lstm)


print("\n--- Previsão com Arquitetura de Deep Learning (Simulada) ---")
print(f"Comentário: '{novo_texto_lstm}'")
print(f"Sentimento Previsto: **{previsao_lstm}** (Classificação Corrigida)")